---
- name: Add packagecloud GPG key.
  rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - "https://packagecloud.io/gpg.key"
    - "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
